In [1]:
import torch
print(torch.__version__)

2.9.0+cu126


In [2]:
if torch.cuda.is_available():
  print("GPU is available")
else:
  print("GPU is not available")

GPU is available


In [3]:
# using empty (it creates memory and shows the numbers which exist on that memory)
x = torch.empty(2,3)
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [4]:
# check type
type(x)

torch.Tensor

In [5]:
#zeros
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [6]:
torch.ones(3,3)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [7]:
torch.rand(2,3)

tensor([[0.8752, 0.8846, 0.8098],
        [0.1869, 0.6386, 0.4828]])

In [8]:
# if we want rand() every time create same random number then we use manual_seed()
torch.manual_seed(100)
torch.rand(2,2)

tensor([[0.1117, 0.8158],
        [0.2626, 0.4839]])

In [9]:
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [10]:
#other ways
print(torch.arange(0,20)
)
torch.arange(0,20,2)

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19])


tensor([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [11]:
#using linspace (using evenly spaced between the rang 0 to 10 and it gives 5 numbers)
torch.linspace(0,10,5)

tensor([ 0.0000,  2.5000,  5.0000,  7.5000, 10.0000])

In [12]:
# using eye() means identity matrix diagonal matrix 1 and other 0
torch.eye(5)


tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [13]:
#using full() 3x3 matrix with 5 value each
torch.full((3,3),5)

tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])

## *Tensor* Shape

In [14]:
x = torch.tensor([[1,2,3],[4,5,6]])
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [15]:
#shape if u want to know matrix size
x.shape

torch.Size([2, 3])

In [16]:
#exmpty_link() , if u want to create the tensor with same shape but value would be different
torch.empty_like(x)

tensor([[416611827831, 498216206446, 498216206368],
        [137438953583, 472446402667, 511101108335]])

In [17]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [18]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [19]:
torch.rand_like(x, dtype=torch.float32)

tensor([[0.6765, 0.7539, 0.2627],
        [0.0428, 0.2080, 0.1180]])

# Tensor Data Type

In [20]:
#find data type
x.dtype


torch.int64

In [21]:
#assign datatype
torch.tensor([1.0,2.0,3.0], dtype=torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [22]:
torch.tensor([1,2,3], dtype=torch.float32)

tensor([1., 2., 3.])

In [23]:
#using to()
x.to(torch.float32)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

# Mathematical Operations

1.Scalar Operation

In [24]:
x=torch.rand(2,2)
x

tensor([[0.1217, 0.7356],
        [0.7118, 0.7876]])

In [25]:
#addition
x+2

tensor([[2.1217, 2.7356],
        [2.7118, 2.7876]])

In [26]:
#subtraction
y = torch.ones_like(x)
y-x

tensor([[0.8783, 0.2644],
        [0.2882, 0.2124]])

In [27]:
#division
x / 3

tensor([[0.0406, 0.2452],
        [0.2373, 0.2625]])

In [28]:
#Int Division
(x*100)//3

tensor([[ 4., 24.],
        [23., 26.]])

In [29]:
#mod
((x*100)//3)%2

tensor([[0., 0.],
        [1., 0.]])

In [30]:
#power
x**2

tensor([[0.0148, 0.5411],
        [0.5066, 0.6203]])

In [31]:
x

tensor([[0.1217, 0.7356],
        [0.7118, 0.7876]])

# Element wise operation

In [32]:
a = torch.rand(2,3)
b = torch.rand(2,3)
print(a)
b

tensor([[0.4183, 0.9014, 0.9969],
        [0.7565, 0.2239, 0.3023]])


tensor([[0.1784, 0.8238, 0.5557],
        [0.9770, 0.4440, 0.9478]])

In [33]:
#addition
a+b

tensor([[0.5967, 1.7253, 1.5526],
        [1.7335, 0.6679, 1.2502]])

In [34]:
#subtraction
a-b

tensor([[ 0.2399,  0.0776,  0.4411],
        [-0.2205, -0.2201, -0.6455]])

In [35]:
#Multiplication
a*b

tensor([[0.0746, 0.7426, 0.5540],
        [0.7391, 0.0994, 0.2866]])

In [36]:
#division
a/b


tensor([[2.3445, 1.0942, 1.7938],
        [0.7743, 0.5042, 0.3190]])

In [37]:
#power
a**b

tensor([[0.8560, 0.9180, 0.9983],
        [0.7614, 0.5145, 0.3218]])

In [38]:
c = torch.tensor([-1,2,-3,4])

In [39]:
#absoulte
torch.abs(c)

tensor([1, 2, 3, 4])

In [40]:
#negative
torch.neg(c)

tensor([ 1, -2,  3, -4])

In [41]:
d = torch.tensor([1.3,2.8,3.1,5.7])

In [42]:
#round
torch.round(d)

tensor([1., 3., 3., 6.])

In [43]:
#clamp
torch.clamp(d, min=2, max=4)

tensor([2.0000, 2.8000, 3.1000, 4.0000])

# Reduction Operation in which whole tesnor is reduced into a single **number**

In [44]:
t = torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)
t

tensor([[9., 9., 8.],
        [0., 7., 0.]])

In [45]:
#add
torch.sum(t)

tensor(33.)

In [46]:
#sum along columns
torch.sum(t,dim=0)

tensor([ 9., 16.,  8.])

In [47]:
#sum along rows
torch.sum(t,dim=1)

tensor([26.,  7.])

In [48]:
#mean
torch.mean(t)

tensor(5.5000)

In [49]:
#mean along column
torch.mean(t,dim=0)

tensor([4.5000, 8.0000, 4.0000])

In [50]:
#max and min
torch.min(t)


tensor(0.)

In [51]:
torch.max(t)

tensor(9.)

In [52]:
#standard deviation
torch.std(t)

tensor(4.3243)

In [53]:
#variance
torch.var(t)

tensor(18.7000)

In [54]:
#argmax (it tells the position of the bigger number in the tensor)
torch.argmax(t)

tensor(0)

# **Matrix Operations**

In [55]:
f = torch.randint(size=(2,3), low=0, high=10,)
d = torch.randint(size=(3,3), low=0, high=10,)
print(f)
print(d)

tensor([[0, 9, 5],
        [7, 3, 9]])
tensor([[4, 0, 5],
        [7, 5, 9],
        [9, 7, 5]])


In [56]:
#matrix multiplication
torch.matmul(f,d)

tensor([[108,  80, 106],
        [130,  78, 107]])

In [57]:
#dot product
vector1 = torch.tensor([1,2,3])
vector2 = torch.tensor([6,7,8])
torch.dot(vector1,vector2)

tensor(44)

In [58]:
#transpose
torch.transpose(d,0,1)

tensor([[4, 7, 9],
        [0, 5, 7],
        [5, 9, 5]])

In [59]:
#determinent
torch.det(torch.rand(3,3))

tensor(-0.0039)

In [60]:
# inverse
torch.inverse(torch.rand(3,3))

tensor([[-2.0841,  3.0302, -0.1651],
        [-2.3201,  0.6904,  1.7824],
        [ 3.6372, -2.5895, -0.6003]])

# **Specail functions**

In [61]:
k = torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)
k

tensor([[8., 8., 3.],
        [3., 5., 0.]])

In [62]:
#log
torch.log(k)

tensor([[2.0794, 2.0794, 1.0986],
        [1.0986, 1.6094,   -inf]])

In [63]:
#exp
torch.exp(k)

tensor([[2.9810e+03, 2.9810e+03, 2.0086e+01],
        [2.0086e+01, 1.4841e+02, 1.0000e+00]])

In [64]:
#squar root
torch.sqrt(k)

tensor([[2.8284, 2.8284, 1.7321],
        [1.7321, 2.2361, 0.0000]])

In [65]:
#sigmoid
torch.sigmoid(k)


tensor([[0.9997, 0.9997, 0.9526],
        [0.9526, 0.9933, 0.5000]])

In [66]:
#softmax
torch.softmax(k,dim=0)

tensor([[0.9933, 0.9526, 0.9526],
        [0.0067, 0.0474, 0.0474]])

In [67]:
#RELU
torch.relu(k)

tensor([[8., 8., 3.],
        [3., 5., 0.]])

# **Inplace Operations**

In [68]:
m = torch.rand(2,3)
n = torch.rand(2,3)
print(m)
print(n)

tensor([[0.7116, 0.1157, 0.6574],
        [0.3451, 0.0453, 0.9798]])
tensor([[0.5548, 0.6868, 0.4920],
        [0.0748, 0.9605, 0.3271]])


In [69]:
m.add_(n)
m


tensor([[1.2663, 0.8025, 1.1494],
        [0.4199, 1.0058, 1.3069]])

In [70]:
m.relu_()

tensor([[1.2663, 0.8025, 1.1494],
        [0.4199, 1.0058, 1.3069]])

# **Copying a tensor**

In [71]:
a = torch.rand(2,3)

In [72]:
b = a.clone()
b


tensor([[0.0103, 0.9516, 0.2855],
        [0.2324, 0.9141, 0.7668]])

In [73]:
id(a)

135456523723600

In [74]:
id(b)

135456523724800

# **Tensor Operations on GPU**

In [75]:
torch.cuda.is_available()

True

In [76]:
device=torch.device('cuda')

In [77]:
#creating a new tensor on GPU
torch.rand((2,3), device=device)

tensor([[0.3563, 0.0303, 0.7088],
        [0.2009, 0.0224, 0.9896]], device='cuda:0')

In [78]:
#moivng an existing tensor to gpu
a = torch.rand(2,3)

In [79]:
b = a.to(device)
b

tensor([[0.1659, 0.4393, 0.2243],
        [0.8935, 0.0497, 0.1780]], device='cuda:0')

In [80]:
b + 5

tensor([[5.1659, 5.4393, 5.2243],
        [5.8935, 5.0497, 5.1780]], device='cuda:0')

# **Reshanping Tensors**

In [81]:
a = torch.ones(4,4)
a


tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [82]:
# reshape
a.reshape(2,2,2,2)

tensor([[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]])

In [83]:
#flatten (it gives a one dimensional vector)
a.flatten()

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [84]:
b =torch.rand(2,3,4) #first number 2 represents the number of blocks
b

tensor([[[0.3011, 0.1893, 0.9186, 0.2131],
         [0.3957, 0.6017, 0.4234, 0.5224],
         [0.4175, 0.0340, 0.9157, 0.3079]],

        [[0.6269, 0.8277, 0.6594, 0.0887],
         [0.4890, 0.5887, 0.7340, 0.8497],
         [0.9112, 0.4847, 0.9436, 0.3904]]])

In [85]:
#permute  is used to rearrange the dimensions of a tensor. When you call b.permute(2,0,1) on a tensor b with shape (2,3,4)
b.permute(2,0,1)

tensor([[[0.3011, 0.3957, 0.4175],
         [0.6269, 0.4890, 0.9112]],

        [[0.1893, 0.6017, 0.0340],
         [0.8277, 0.5887, 0.4847]],

        [[0.9186, 0.4234, 0.9157],
         [0.6594, 0.7340, 0.9436]],

        [[0.2131, 0.5224, 0.3079],
         [0.0887, 0.8497, 0.3904]]])

In [86]:
b.permute(2,0,1).shape

torch.Size([4, 2, 3])

In [87]:
#unsqueeze operation is used to add a new dimension of size 1 at the specified position (index 0 in this case) of the tensor. This is commonly used in deep learning to add a batch dimension to a single image or data sample.
#image size
c = torch.rand(226,226,3)
c.unsqueeze(0).shape

torch.Size([1, 226, 226, 3])

In [88]:
#The squeeze(0) operation removes dimensions of size 1 from a tensor.d.squeeze(0) removes this dimension of size 1 at index 0.
#The resulting shape is (20), effectively flattening the tensor into a 1D vector.
d = torch.rand(1,20)
d.squeeze(0).shape

torch.Size([20])

# **Numpy vs Pytorch**

In [89]:
import numpy as np

In [90]:
#conversion of tensor into the array
a = torch.rand(2,3)
b = a.numpy()

In [91]:
b


array([[0.66009915, 0.23275459, 0.9062091 ],
       [0.9867381 , 0.5495048 , 0.18928719]], dtype=float32)

In [92]:
##conversion of array into the tensor
c = np.array([[1,2,3],[4,5,6]])
d = torch.from_numpy(c)
d

tensor([[1, 2, 3],
        [4, 5, 6]])