In [112]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [113]:

df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [114]:
df.shape

(569, 33)

In [115]:
df.drop(columns = ["Unnamed: 32", "id"], inplace=True)

In [116]:
df.head()

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0         M        17.99         10.38          122.80     1001.0   
1         M        20.57         17.77          132.90     1326.0   
2         M        19.69         21.25          130.00     1203.0   
3         M        11.42         20.38           77.58      386.1   
4         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0         0.2419  ...         25.38          17.33           184.60   
1         0.1812  ...         24.99          23.41           158.80   
2         0.2069  ...         23.57          25.53           152.50   
3         0.2597  ...         14.91          26.50            98.87   
4         0.1809  ...         22.54          16.67           152.20   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   concave points_worst  symmetry_worst  fractal_dimension_worst  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 31 columns]

# **Train test split**

In [117]:
x_train, x_test, y_train, y_test = train_test_split(df.iloc[:,1:], df.iloc[:,0], test_size=0.2)

# **Scaling**

scaler = StandardScaler(): This line creates an instance of the StandardScaler class. StandardScaler standardizes features by removing the mean and scaling to unit variance. This results in a distribution with a mean of 0 and a standard deviation of 1.

x_train = scaler.fit_transform(x_train): This is applied to your training data (x_train).

fit: This method calculates the mean and standard deviation of each feature in x_train.
transform: This method then uses the calculated means and standard deviations to scale the x_train data.
x_test = scaler.transform(x_test): This is applied to your test data (x_test).

transform: Crucially, for the test set, we only use the transform method. This means it applies the same mean and standard deviation that were calculated from the training data to scale the test data. We do not use fit_transform on x_test because we want to prevent data leakage from the test set into the training process.
**Why do we do this?**

Feature scaling is an important preprocessing step for many machine learning algorithms, especially those that are sensitive to the magnitude of feature values. Here's why it's often done:

**Algorithm Performance**: Algorithms like Logistic Regression, Support Vector Machines (SVMs), k-Nearest Neighbors (k-NN), and Neural Networks are often sensitive to the scale of features. If one feature has a much larger range of values than another, the algorithm might disproportionately weigh that feature.
**Faster Convergence**: For gradient-descent-based algorithms, scaling can lead to faster convergence during training.
**Preventing Domination**: Features with larger values might dominate the distance calculations or cost functions, even if they are not more important predictors. Scaling ensures that all features contribute equally to the distance metrics or cost functions.
In essence, it brings all your features to a similar scale, which helps many models perform better and more consistently.



---



In [118]:
scaler = StandardScaler()
x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)


In [119]:
x_train

array([[ 1.51170948,  2.30419767,  1.67658014, ...,  1.19448112,
        -0.11802233,  0.96989456],
       [ 0.12367733, -0.86570797,  0.01510609, ..., -0.85907063,
        -0.58687716, -1.52996278],
       [-1.67851665, -0.58700832, -1.6483981 , ..., -1.34976635,
         0.34920454, -0.5460924 ],
       ...,
       [-0.20787691,  0.08914128, -0.26261831, ...,  0.01493864,
        -0.01057643, -0.56790517],
       [-0.67711045,  0.56656591, -0.71412347, ..., -1.17593108,
        -0.74479008, -1.03171337],
       [ 2.12986145,  0.41873391,  2.232841  , ...,  1.04345136,
        -0.0936028 ,  0.28566266]])

In [120]:
y_train

256    M
311    B
46     B
398    B
66     B
      ..
436    B
557    B
171    M
50     B
272    M
Name: diagnosis, Length: 455, dtype: object

# Label **Encoder**
Many machine learning algorithms require their input, including the target variable, to be in a numerical format. They cannot directly work with categorical labels (like strings or objects). LabelEncoder provides a straightforward way to convert these categorical target labels into integers, making them suitable for model training.

In [121]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.fit_transform(y_test)

In [122]:
y_train

array([1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0,
       0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1,
       1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0,
       1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0,
       1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1,
       1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0,
       0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1,

In [123]:
y_test

array([1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1,
       0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0,
       0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 1, 0, 1])

# **Numpy arrays to pytorch tensors**

In [124]:
x_train_tensor = torch.from_numpy(x_train).float()
x_test_tensor = torch.from_numpy(x_test).float()
y_train_tensor = torch.from_numpy(y_train).float()
y_test_tensor = torch.from_numpy(y_test).float()

In [125]:
x_train_tensor

tensor([[ 1.5117,  2.3042,  1.6766,  ...,  1.1945, -0.1180,  0.9699],
        [ 0.1237, -0.8657,  0.0151,  ..., -0.8591, -0.5869, -1.5300],
        [-1.6785, -0.5870, -1.6484,  ..., -1.3498,  0.3492, -0.5461],
        ...,
        [-0.2079,  0.0891, -0.2626,  ...,  0.0149, -0.0106, -0.5679],
        [-0.6771,  0.5666, -0.7141,  ..., -1.1759, -0.7448, -1.0317],
        [ 2.1299,  0.4187,  2.2328,  ...,  1.0435, -0.0936,  0.2857]])

In [126]:
y_train_tensor.shape

torch.Size([455])

# Defining **Model**

In [127]:
import torch
import torch.nn as nn
class MySimpeNN(nn.Module):

  def __init__(self, num_features):
    super().__init__()
    self.linear = nn.Linear(num_features, 1)
    self.sigmoid = nn.Sigmoid()

  def forward(self, features):
    out = self.linear(features)
    out = self.sigmoid(out)
    return out

# **Important Parameters**

In [128]:
learning_rate = 0.1
epochs = 25

# **Loss function**

In [153]:
loss_function = nn.BCELoss()

In [154]:
type(loss_function)

torch.nn.modules.loss.BCELoss

In [ ]:
#define optimizer

## **Traning pipline of nn module**

In [163]:
# create model
model = MySimpeNN(x_train_tensor.shape[1])

#define optimizer
optimizer = torch.optim.SGD(model.parameters(), lr=learning_rate)

#define loop
for epoch in range(epochs):
  #forward pass
  y_pred = model(x_train_tensor)

  #loss calculation
  loss = loss_function(y_pred, y_train_tensor.view(-1,1))

  #zero gradients clear them before the backward pass it is best and then update the parameters
  optimizer.zero_grad()

  #backwardpass
  loss.backward()

  #update weights
  optimizer.step()

  #print loss in each epoch
  print(f"Epoch {epoch}/{epoch}, Loss: {loss.item()}")

Epoch 0/0, Loss: 0.7690855860710144
Epoch 1/1, Loss: 0.5655628442764282
Epoch 2/2, Loss: 0.46242138743400574
Epoch 3/3, Loss: 0.40112602710723877
Epoch 4/4, Loss: 0.35979902744293213
Epoch 5/5, Loss: 0.32958313822746277
Epoch 6/6, Loss: 0.30625656247138977
Epoch 7/7, Loss: 0.28753939270973206
Epoch 8/8, Loss: 0.27208343148231506
Epoch 9/9, Loss: 0.25903505086898804
Epoch 10/10, Loss: 0.24782446026802063
Epoch 11/11, Loss: 0.2380550056695938
Epoch 12/12, Loss: 0.22944094240665436
Epoch 13/13, Loss: 0.22177034616470337
Epoch 14/14, Loss: 0.21488238871097565
Epoch 15/15, Loss: 0.2086523473262787
Epoch 16/16, Loss: 0.2029818743467331
Epoch 17/17, Loss: 0.19779212772846222
Epoch 18/18, Loss: 0.19301912188529968
Epoch 19/19, Loss: 0.1886102706193924
Epoch 20/20, Loss: 0.1845218390226364
Epoch 21/21, Loss: 0.18071720004081726
Epoch 22/22, Loss: 0.17716529965400696
Epoch 23/23, Loss: 0.1738397628068924
Epoch 24/24, Loss: 0.17071779072284698


In [157]:
model.linear.weight

Parameter containing:
tensor([[ 0.2747,  0.2407,  0.1217,  0.3106,  0.1062,  0.2086,  0.2097,  0.1655,
          0.1253,  0.0447,  0.1740,  0.1084,  0.0888,  0.2236, -0.1537, -0.1410,
         -0.0950,  0.2360, -0.1141,  0.0736,  0.3698,  0.3045,  0.1798,  0.1855,
          0.1871,  0.1182,  0.1424,  0.3060,  0.2977,  0.0206]],
       requires_grad=True)

# **Evaluation**

In [162]:
with torch.no_grad():
  y_pred = model.forward(x_test_tensor)
  y_pred = (y_pred > 0.9).float()
  accuracy = (y_pred == y_test_tensor).float().mean()
  print(f"Accuracy: {accuracy}")

Accuracy: 0.5738688707351685


# **Pytorch NN module**
our module should inherit from (nn.Module) else we cannot access the ofrings of
nn.Module

In [166]:
#create model class
import torch
import torch.nn as nn


class Model(nn.Module):
  def __init__(self, num_features):
#invoking the parent class(nn.Module) constructor through super() keyword
    super().__init__()
    # 3 in the parameter is the number of neuron and num_features is the number of inputs
    self.linear1 = nn.Linear(num_features, 3)
    self.relu = nn.ReLU()
    self.linear2 = nn.Linear(3,1)
    self.sigmoid = nn.Sigmoid()

    #forward pass
  def forward(self, features):
      out = self.linear1(features) #z = wx+b
      out = self.relu(out)
      out = self.linear2(out)
      out = self.sigmoid(out)
      return out


# Sequential **Container**

In [167]:
#create model class
import torch
import torch.nn as nn


class Model(nn.Module):
  def __init__(self, num_features):
#invoking the parent class(nn.Module) constructor through super() keyword
    super().__init__()
    self.network = nn.Sequential(
        nn.Linear(num_features, 3),
        nn.ReLU(),
        nn.Linear(3,1),
        nn.Sigmoid(),
    )

    #forward pass
  def forward(self, features):
      out  = self.network(features)
      return out


### What is `nn.Sequential`?
`torch.nn.Sequential` is a module that contains other modules (layers) and passes the input through them in the order they are added. It's essentially a linear stack of neural network layers. When you call the `forward` method on an `nn.Sequential` module, the input is passed to the first layer, its output becomes the input to the second layer, and so on, until the last layer's output is returned.

### How it Helps:

1.  **Simplicity and Readability**: It makes your code cleaner and easier to understand, especially for models with a straightforward, feed-forward architecture. Instead of defining each layer and explicitly chaining them in the `forward` method, you list them once.

2.  **Modularity**: Each layer within `nn.Sequential` is an `nn.Module` itself. This means you can combine different types of layers (linear, convolutional, activation functions, pooling, etc.) seamlessly.

3.  **Automatic `forward` pass**: You don't need to write the `forward` method yourself when using `nn.Sequential` for simple, sequential models. PyTorch handles the data flow through the layers automatically.

4.  **Parameter Management**: All parameters (weights and biases) of the layers within `nn.Sequential` are automatically registered as parameters of the `Sequential` module itself. This simplifies optimization, as you only need to optimize the parameters of the `Sequential` module.

5.  **Easy Inspection**: As you saw in the previous example, you can easily access individual layers and their parameters by indexing the `nn.Sequential` object (e.g., `model.network[0]` for the first layer, `model.network[2]` for the second linear layer, etc.).

### When to Use It (and When Not To):

*   **Ideal for**: Models with a clear, linear data flow, where the output of one layer directly feeds into the next. Many common architectures, like simple fully connected networks or stacked convolutional layers, fit this pattern.

*   **Less Suitable for**: Models with more complex architectures, such as those with multiple inputs/outputs, skip connections (e.g., ResNets), branching paths, or custom logic that depends on the intermediate outputs of multiple layers. For these, defining a custom `nn.Module` with an explicit `forward` method is necessary.

In [168]:
#create dataset
features = torch.rand(10,5)

#create model
model = Model(features.shape[1])

#call model for forward pass

# model.forward(features) it will work but it is not recommended
model(features)


tensor([[0.3723],
        [0.3975],
        [0.3922],
        [0.3826],
        [0.3976],
        [0.3722],
        [0.3961],
        [0.3910],
        [0.3730],
        [0.3880]], grad_fn=<SigmoidBackward0>)

In [169]:
print("Weights of the first linear layer:")
print(model.network[0].weight)

print("Bias of the first linear layer:")
print(model.network[0].bias)

print("Weights of the second linear layer:")
print(model.network[2].weight)

print("Bias of the second linear layer:")
print(model.network[2].bias)

Weights of the first linear layer:
Parameter containing:
tensor([[ 0.0522, -0.1577, -0.1760,  0.1425, -0.0881],
        [ 0.3115, -0.2441, -0.0595,  0.3427, -0.1414],
        [-0.2918, -0.2046,  0.0719,  0.3655,  0.1751]], requires_grad=True)
Bias of the first linear layer:
Parameter containing:
tensor([0.3750, 0.1476, 0.0642], requires_grad=True)
Weights of the second linear layer:
Parameter containing:
tensor([[-0.2683,  0.0723, -0.3695]], requires_grad=True)
Bias of the second linear layer:
Parameter containing:
tensor([-0.3868], requires_grad=True)


In [ ]:
#show model weights

#linear1 has 15 weights cuz 5x3, we have 5 input features and 3 number of neuron
#linear2 has 3 number of weights cuz it has 1 neuron and 3 input which are of linear 1
model.linear1.weight

In [149]:
#model bias
model.linear1.bias

Parameter containing:
tensor([ 0.3132, -0.1438,  0.2104], requires_grad=True)

In [151]:
!pip install torchinfo

In [171]:
from torchinfo import summary

summary(model, input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Sequential: 1-1                        [10, 1]                   --
│    └─Linear: 2-1                       [10, 3]                   18
│    └─ReLU: 2-2                         [10, 3]                   --
│    └─Linear: 2-3                       [10, 1]                   4
│    └─Sigmoid: 2-4                      [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00